# Лабораторна робота №5
## Гаркот Софія

Інструкції

Використовуючи запропоновані дані, створіть складне представлення даних з наступними елементами

- карта, котра відображає рівень приросту / скорочення населення за регіонами станом на останній доступний рік

- лінійний графік, котрий відображає рівень приросту / скорочення населення за регіонами за всіма роками (одна лінія на графіку - один регіон)

В якості прикладу можете використовувати приєднане зображення

In [1]:
import altair as alt
import pandas as pd
import altair_viewer

alt.renderers.enable('altair_viewer')

RendererRegistry.enable('altair_viewer')

In [2]:
data = pd.read_csv('population_trends.csv')
data.head()

    region  year  rate
0  Ukraine  1989   1.7
1  Ukraine  1990   0.5
2  Ukraine  1991  -0.8
3  Ukraine  1992  -2.0
4  Ukraine  1993  -3.5

In [3]:
data.shape

(868, 3)

In [4]:
set(data['region'])

{'Cherkasy',
 'Chernihiv',
 'Chernivtsi',
 'Crimea',
 "Dnipropetrovs'k",
 "Donets'k",
 "Ivano-Frankivs'k",
 'Kharkiv',
 'Kherson',
 "Khmel'nyts'kyy",
 'Kirovohrad',
 'Kyiv',
 'Kyiv City',
 "L'viv",
 "Luhans'k",
 'Mykolayiv',
 'Odesa',
 'Poltava',
 'Rivne',
 "Sevastopol'",
 'Sumy',
 "Ternopil'",
 'Transcarpathia',
 'Ukraine',
 'Vinnytsya',
 'Volyn',
 'Zaporizhzhya',
 'Zhytomyr'}

In [5]:
import geopandas as gpd
ukraine = gpd.read_file('ukraine.json')
ukraine.head()

,GID_0,NAME_0,GID_1,NAME_1,VARNAME_1,NL_NAME_1,TYPE_1,ENGTYPE_1,CC_1,HASC_1,geometry
0,UKR,Ukraine,UKR.1_1,Cherkasy,Cherkas'ka Oblast'|Cherkasskaya Oblast'|Cherkassy,None,Oblast',Region,None,UA.CK,"MULTIPOLYGON (((31.32614 48.74507, 31.31716 48..."
1,UKR,Ukraine,UKR.2_1,Chernihiv,Chernigov|Tschernigow,None,Oblast',Region,None,UA.CH,"MULTIPOLYGON (((33.09283 50.50966, 33.09261 50..."
2,UKR,Ukraine,UKR.3_1,Chernivtsi,Chernivets'ka Oblast'|Chernovitskaya Oblast'|C...,None,Oblast',Region,None,UA.CV,"MULTIPOLYGON (((24.93280 47.72794, 24.93301 47..."
3,UKR,Ukraine,UKR.4_1,Crimea,Crimée|Criméia|Krim|Krymskaya Respublika|Respu...,None,Autonomous Republic,Autonomous Republic,None,UA.KR,"MULTIPOLYGON (((33.79291 44.39153, 33.79465 44..."
4,UKR,Ukraine,UKR.5_1,Dnipropetrovs'k,Dnipropetrovsk|Dniepropietrovsk|Dnjepropetrowsk,None,Oblast',Region,None,UA.DP,"MULTIPOLYGON (((33.93176 47.48407, 33.92332 47..."

In [6]:
ukraine.shape

(27, 11)

In [7]:
diff = list(set(ukraine['NAME_1']).symmetric_difference(set(data['region'])))

In [8]:
new_df = data[data['year']==2019]
new_df = new_df[new_df['region']!=diff[0]]

In [9]:
cols = [i for i in ukraine.columns]
cols[3] = 'region'
ukraine.columns = cols
ukraine.head()

,GID_0,NAME_0,GID_1,region,VARNAME_1,NL_NAME_1,TYPE_1,ENGTYPE_1,CC_1,HASC_1,geometry
0,UKR,Ukraine,UKR.1_1,Cherkasy,Cherkas'ka Oblast'|Cherkasskaya Oblast'|Cherkassy,None,Oblast',Region,None,UA.CK,"MULTIPOLYGON (((31.32614 48.74507, 31.31716 48..."
1,UKR,Ukraine,UKR.2_1,Chernihiv,Chernigov|Tschernigow,None,Oblast',Region,None,UA.CH,"MULTIPOLYGON (((33.09283 50.50966, 33.09261 50..."
2,UKR,Ukraine,UKR.3_1,Chernivtsi,Chernivets'ka Oblast'|Chernovitskaya Oblast'|C...,None,Oblast',Region,None,UA.CV,"MULTIPOLYGON (((24.93280 47.72794, 24.93301 47..."
3,UKR,Ukraine,UKR.4_1,Crimea,Crimée|Criméia|Krim|Krymskaya Respublika|Respu...,None,Autonomous Republic,Autonomous Republic,None,UA.KR,"MULTIPOLYGON (((33.79291 44.39153, 33.79465 44..."
4,UKR,Ukraine,UKR.5_1,Dnipropetrovs'k,Dnipropetrovsk|Dniepropietrovsk|Dnjepropetrowsk,None,Oblast',Region,None,UA.DP,"MULTIPOLYGON (((33.93176 47.48407, 33.92332 47..."

In [10]:
merged = ukraine.merge(new_df)
merged.head()

,GID_0,NAME_0,GID_1,region,VARNAME_1,NL_NAME_1,TYPE_1,ENGTYPE_1,CC_1,HASC_1,geometry,year,rate
0,UKR,Ukraine,UKR.1_1,Cherkasy,Cherkas'ka Oblast'|Cherkasskaya Oblast'|Cherkassy,None,Oblast',Region,None,UA.CK,"MULTIPOLYGON (((31.32614 48.74507, 31.31716 48...",2019,-10.0
1,UKR,Ukraine,UKR.2_1,Chernihiv,Chernigov|Tschernigow,None,Oblast',Region,None,UA.CH,"MULTIPOLYGON (((33.09283 50.50966, 33.09261 50...",2019,-12.5
2,UKR,Ukraine,UKR.3_1,Chernivtsi,Chernivets'ka Oblast'|Chernovitskaya Oblast'|C...,None,Oblast',Region,None,UA.CV,"MULTIPOLYGON (((24.93280 47.72794, 24.93301 47...",2019,-3.1
3,UKR,Ukraine,UKR.4_1,Crimea,Crimée|Criméia|Krim|Krymskaya Respublika|Respu...,None,Autonomous Republic,Autonomous Republic,None,UA.KR,"MULTIPOLYGON (((33.79291 44.39153, 33.79465 44...",2019,NaN
4,UKR,Ukraine,UKR.5_1,Dnipropetrovs'k,Dnipropetrovsk|Dniepropietrovsk|Dnjepropetrowsk,None,Oblast',Region,None,UA.DP,"MULTIPOLYGON (((33.93176 47.48407, 33.92332 47...",2019,-8.9

In [11]:
import numpy as np
average = 0
lst = []
for i,r in merged.iterrows():
    if np.isnan(r['rate']):
        r['rate'] = average
        lst.append("None")
        merged.iloc[i,:] = r
    else:
        lst.append(str(r['rate']))
merged['str_rate'] = lst

In [12]:
merged.head()

,GID_0,NAME_0,GID_1,region,VARNAME_1,NL_NAME_1,TYPE_1,ENGTYPE_1,CC_1,HASC_1,geometry,year,rate,str_rate
0,UKR,Ukraine,UKR.1_1,Cherkasy,Cherkas'ka Oblast'|Cherkasskaya Oblast'|Cherkassy,None,Oblast',Region,None,UA.CK,"MULTIPOLYGON (((31.32614 48.74507, 31.31716 48...",2019,-10.0,-10.0
1,UKR,Ukraine,UKR.2_1,Chernihiv,Chernigov|Tschernigow,None,Oblast',Region,None,UA.CH,"MULTIPOLYGON (((33.09283 50.50966, 33.09261 50...",2019,-12.5,-12.5
2,UKR,Ukraine,UKR.3_1,Chernivtsi,Chernivets'ka Oblast'|Chernovitskaya Oblast'|C...,None,Oblast',Region,None,UA.CV,"MULTIPOLYGON (((24.93280 47.72794, 24.93301 47...",2019,-3.1,-3.1
3,UKR,Ukraine,UKR.4_1,Crimea,Crimée|Criméia|Krim|Krymskaya Respublika|Respu...,None,Autonomous Republic,Autonomous Republic,None,UA.KR,"MULTIPOLYGON (((33.79291 44.39153, 33.79465 44...",2019,0.0,None
4,UKR,Ukraine,UKR.5_1,Dnipropetrovs'k,Dnipropetrovsk|Dniepropietrovsk|Dnjepropetrowsk,None,Oblast',Region,None,UA.DP,"MULTIPOLYGON (((33.93176 47.48407, 33.92332 47...",2019,-8.9,-8.9

In [13]:
data2019 = data[data['year'] == 2019]
data2019

               region  year  rate
30            Ukraine  2019  -6.6
61             Crimea  2019   NaN
92          Vinnytsya  2019  -7.9
123             Volyn  2019  -2.8
154   Dnipropetrovs'k  2019  -8.9
185          Donets'k  2019   NaN
216          Zhytomyr  2019  -8.5
247    Transcarpathia  2019  -2.0
278      Zaporizhzhya  2019  -9.6
309  Ivano-Frankivs'k  2019  -4.0
340              Kyiv  2019  -8.1
371        Kirovohrad  2019  -9.6
402          Luhans'k  2019   NaN
433             L'viv  2019  -4.3
464         Mykolayiv  2019  -8.1
495             Odesa  2019  -5.1
526           Poltava  2019  -9.9
557             Rivne  2019  -1.6
588              Sumy  2019 -10.2
619         Ternopil'  2019  -6.6
650           Kharkiv  2019  -8.4
681           Kherson  2019  -7.4
712    Khmel'nyts'kyy  2019  -7.5
743          Cherkasy  2019 -10.0
774        Chernivtsi  2019  -3.1
805         Chernihiv  2019 -12.5
836         Kyiv City  2019  -0.2
867       Sevastopol'  2019   NaN

In [14]:
data.head()

    region  year  rate
0  Ukraine  1989   1.7
1  Ukraine  1990   0.5
2  Ukraine  1991  -0.8
3  Ukraine  1992  -2.0
4  Ukraine  1993  -3.5

In [15]:
cols_new_df = list(set(merged['region']))
cols_new_df.append('year')
cols_new_df

['Kherson',
 'Chernihiv',
 'Transcarpathia',
 "Sevastopol'",
 'Volyn',
 'Cherkasy',
 'Zaporizhzhya',
 "Luhans'k",
 "Ternopil'",
 "Donets'k",
 'Kyiv City',
 'Crimea',
 'Vinnytsya',
 'Chernivtsi',
 'Rivne',
 'Kharkiv',
 'Kyiv',
 'Mykolayiv',
 'Kirovohrad',
 "Ivano-Frankivs'k",
 "Khmel'nyts'kyy",
 "L'viv",
 'Sumy',
 "Dnipropetrovs'k",
 'Zhytomyr',
 'Poltava',
 'Odesa',
 'year']

In [16]:
year_region_rate = {}
for i, r in data.iterrows():
    if r['region'] != 'Ukraine':
        region = r['region']
        year = r['year']
        rate = r['rate']
        if year not in year_region_rate:
            year_region_rate[year] = {}
        
        if not np.isnan(rate):
            year_region_rate[year][region] = rate
        else:
            year_region_rate[year][region] = average

In [17]:
final = [cols_new_df]
for y in year_region_rate:
    one_year_data = []
    for i in cols_new_df[:-1]:
#         print("i", i, 'y', y, 'r', r)
        one_year_data.append(year_region_rate[y][i])
        
    one_year_data.append(y)
    final.append(one_year_data)

d2 = pd.DataFrame(data=final[1:], columns=final[0])
d2.head()

,Kherson,Chernihiv,Transcarpathia,Sevastopol',Volyn,Cherkasy,Zaporizhzhya,Luhans'k,Ternopil',Donets'k,...,Kirovohrad,Ivano-Frankivs'k,Khmel'nyts'kyy,L'viv,Sumy,Dnipropetrovs'k,Zhytomyr,Poltava,Odesa,year
0,3.7,-2.1,8.0,0.0,5.2,-0.7,2.0,0.6,2.0,0.1,...,-1.1,5.4,0.2,4.7,-1.7,1.7,1.5,-1.3,1.4,1989
1,2.7,-4.0,7.6,3.2,4.0,-2.1,0.5,-0.6,1.4,-1.2,...,-1.9,5.1,-0.6,3.6,-3.1,0.5,-0.3,-2.5,0.2,1990
2,1.5,-5.7,6.4,1.7,2.0,-3.3,-0.7,-1.7,0.4,-2.5,...,-2.8,3.7,-1.7,2.4,-4.0,-0.8,-1.0,-3.4,-1.2,1991
3,0.5,-6.7,5.8,-0.7,2.4,-4.1,-2.5,-4.0,-0.1,-4.3,...,-3.8,3.1,-2.2,2.0,-5.3,-2.7,-1.7,-4.9,-1.9,1992
4,-1.2,-8.5,4.4,-2.7,1.4,-6.2,-4.1,-5.9,-1.2,-6.2,...,-5.6,2.4,-3.6,1.1,-7.5,-4.4,-2.8,-6.7,-3.2,1993

In [28]:
data["Year"] = data["year"].astype("str")

In [35]:
country_map = alt.Chart(merged, title='Population trends in Ukraine in 2019').project(type = 'equalEarth').mark_geoshape().encode(
    color = alt.Color('rate:Q', title='Rate of population change', scale=alt.Scale(scheme='reds', reverse=True), legend=alt.Legend(title='Rate')),
    tooltip = [
        alt.Tooltip('region:O', title='Region name'),
        alt.Tooltip('str_rate:O', title='Population increase rate in 2019')
    ]
).properties(width = 700, height = 400)

In [36]:
side_line_plot = alt.Chart(data, title='Population trends in Ukraine through all the years').mark_line().encode(
    x = alt.X(field='Year', 
              type='temporal'
             ),
    y = alt.Y('rate:Q'),
    color = alt.Color('region:O', scale = alt.Scale(type = 'quantize', scheme = 'warmgreys'),
                      title='Region name'),
    detail = alt.Detail('region:N'),
    tooltip = [
        alt.Tooltip('region:O', title='Region name')
    ]
).properties(width = 600, height = 400)

In [38]:
alt.hconcat(country_map, 
            side_line_plot
           ).configure_title(fontSize=17)

Displaying chart at http://localhost:17926/